# This is a basic workflow to help you get started with Actions

name: run-backend-tests-on-push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: ['5.0']
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd ./backend
          npm install
          npm install --save-dev jest
          npm test presManager
      - name: Run test for userStore
        run: |
          cd ./backend
          npm install
          npm install --save-dev jest
          npm test userStore
          npm test parser
          
      - name: Run test for parser
        run: |
          cd ./backend
          npm install
          npm install --save-dev jest
          npm test parser 
